version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Expose the app on port 3000
    environment:
      MONGODB_URI: mongodb+srv://<username>:<password>@<url>/  # Replace with your actual database name
      REDIS_HOST: redis
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
